### ISSUE TITLE
Error: RequestBody decorator is only used in controllers class.

### ISSUE THREAD

**Issue by dsp1589** [thinkkoa/koatty#23]
Am unable to run the app and facing this error message. Google Search did not help at all. Error shown at the line 10(marked with Arrow). Same RequestBody decorator works just fine in other controllers. 

`
import { Controller, BaseController, GetMapping, PostMapping, RequestBody, Header, Middleware, Param } from "koatty";
import { App } from '../../App';
import { google } from 'googleapis';

@Controller()
export class InAppVerifycontroller extends BaseController {
    app: App;

    @PostMapping("/verifyPurchase")
    async verifyPurchase(@RequestBody() requestBody: any) {  <-------------------------
        const packageName = requestBody.post.packageName;
        const subscriptionId = requestBody.post.subscriptionId;
    }
}`

Logs:

[2020-10-06 21:11:10.405] [ERROR] Error: RequestBody decorator is only used in controllers class.
    at /Users/dhanasekarapandiansrinivasan/Development/middleware/node_modules/koatty/src/core/RequestMapping.ts:214:19
    at /Users/dhanasekarapandiansrinivasan/Development/middleware/node_modules/tslib/tslib.js:101:41
    at DecorateProperty (/Users/dhanasekarapandiansrinivasan/Development/middleware/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate (/Users/dhanasekarapandiansrinivasan/Development/middleware/node_modules/reflect-metadata/Reflect.js:123:24)
    at Object.__decorate (/Users/dhanasekarapandiansrinivasan/Development/middleware/node_modules/tslib/tslib.js:95:96)
    at Object.<anonymous> (/Users/dhanasekarapandiansrinivasan/Development/middleware/src/controller/InApp/InAppVerifycontroller.ts:10:5)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Module._compile (/Users/dhanasekarapandiansrinivasan/Development/middleware/node_modules/ts-node/src/index.ts:858:23)
    at internal/modules/cjs/loader.js:1158:10
    at Object..ts (/Users/dhanasekarapandiansrinivasan/Development/middleware/node_modules/ts-node/src/index.ts:861:12)

**Comment by dsp1589** [comment]
Created controller using "koatty controller InAppVerifycontroller" command and it worked.

**Comment by richenlin** [comment]
The possible reason is that the controller class is not loaded correctly in the IOC container. Change ʻInAppVerifycontroller` to ʻInAppVerifyController` and try. This is because, when the IOC container cannot accurately determine the type of bean, it will automatically determine it based on the file suffix

**Comment by dsp1589** [comment]
@richenlin ok got it. Thank you
